spring:
  profiles:
    group:
      default: dev, test
  config:
    import:
      - classpath:/aws.yml
      - classpath:/redis.yml
      - classpath:/jpa.yml
      - classpath:/security.yml
      - classpath:/logging.yml
      - classpath:/application-secret.yml
      - classpath:/db.yml
      - classpath:/kafka.yml