spring:
  redis:
    host: localhost
    port: 6379
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

decorator:
  datasource:
    p6spy:
      enable-logging=true: