spring:
  profiles:
    active: secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: ssafy

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  config:
    import:
      - classpath:/aws.yml

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          naver:
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        #네이버가 provider로 등록되어있지 않기 때문에 내가 직접 등록
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 여기로 요청하면 네이버 로그인 창 뜸
            token-uri: https://nid.naver.com/oauth2.0/token # 토큰을 받기위한 주소
            user-info-uri: https://openapi.naver.com/v1/nid/me # 프로필 정보를 받기위한 주소
            user-name-attribute: response # 회원정보를 json으로 받는데 response 키값으로 네이버가 리턴
