spring:
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      redirect-to: "http://localhost:3000/oauth2/redirect"
      client:
        registration:
          naver:
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        #네이버가 provider로 등록되어있지 않기 때문에 내가 직접 등록
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 여기로 요청하면 네이버 로그인 창 뜸
            token-uri: https://nid.naver.com/oauth2.0/token # 토큰을 받기위한 주소
            user-info-uri: https://openapi.naver.com/v1/nid/me # 프로필 정보를 받기위한 주소
            user-name-attribute: response # 회원정보를 json으로 받는데 response 키값으로 네이버가 리턴
---
spring:
  config:
    activate:
      on-profile: prod
  security:
    oauth2:
      redirect-to: "https://i10b308.p.ssafy.io/oauth2/redirect"
      client:
        registration:
          naver:
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: https://i10b308.p.ssafy.io/login/oauth2/code/naver

        #네이버가 provider로 등록되어있지 않기 때문에 내가 직접 등록
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 여기로 요청하면 네이버 로그인 창 뜸
            token-uri: https://nid.naver.com/oauth2.0/token # 토큰을 받기위한 주소
            user-info-uri: https://openapi.naver.com/v1/nid/me # 프로필 정보를 받기위한 주소
            user-name-attribute: response # 회원정보를 json으로 받는데 response 키값으로 네이버가 리턴
